# ---------- Build stage ----------
FROM gradle:8.14.3-jdk17 AS build
WORKDIR /home/app
COPY . .
# Resolve/configure first, then compile Kotlin in isolation so Render logs keep
# compiler errors close to the end of the stream (easier to debug than full build tail).
RUN ./gradlew help --no-daemon --stacktrace --console=plain
RUN /bin/bash -o pipefail -c '\
  ./gradlew clean compileKotlin -x test --no-daemon --stacktrace --console=plain --warning-mode=all 2>&1 | tee /tmp/compileKotlin.log \
  || { \
    echo ""; \
    echo "========== Extracted Kotlin/Gradle failure lines =========="; \
    grep -nE "(^e: |error:|Execution failed for task|\* What went wrong:|Caused by:|Compilation error)" /tmp/compileKotlin.log | tail -n 200 || true; \
    echo "========== Last 220 lines of compileKotlin log =========="; \
    tail -n 220 /tmp/compileKotlin.log || true; \
    exit 1; \
  }'
# Package the application after Kotlin compilation passes.
RUN ./gradlew build -x test --no-daemon --stacktrace --console=plain

# ---------- Runtime stage ----------
# Use Eclipse Temurin for the JDK—this image is available on Docker Hub.
FROM eclipse-temurin:17
WORKDIR /app
# Copy the fat jar generated by the build.  Adjust the jar path if your jar name differs.
COPY --from=build /home/app/build/libs/*.jar ./app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
