# ---------- Build stage ----------
FROM gradle:8.14.3-jdk17 AS build
WORKDIR /home/app
COPY . .
# Compile and package the application.  Using ./gradlew ensures the correct Gradle version is used.
RUN ./gradlew clean build -x test --no-daemon --stacktrace --info --console=plain

# ---------- Runtime stage ----------
# Use Eclipse Temurin for the JDK—this image is available on Docker Hub.
FROM eclipse-temurin:17
WORKDIR /app
# Copy the fat jar generated by the build.  Adjust the jar path if your jar name differs.
COPY --from=build /home/app/build/libs/*.jar ./app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
