# ---------- Build stage ----------
FROM gradle:8.14.3-jdk17 AS build
WORKDIR /home/app
COPY . .
# Resolve/configure first, then compile Kotlin in isolation so Render logs keep
# compiler errors close to the end of the stream (easier to debug than full build tail).
RUN ./gradlew help --no-daemon --stacktrace --console=plain
RUN ./gradlew clean compileKotlin -x test --no-daemon --stacktrace --console=plain --warning-mode=all
# Package the application after Kotlin compilation passes.
RUN ./gradlew build -x test --no-daemon --stacktrace --console=plain

# ---------- Runtime stage ----------
# Use Eclipse Temurin for the JDK—this image is available on Docker Hub.
FROM eclipse-temurin:17
WORKDIR /app
# Copy the fat jar generated by the build.  Adjust the jar path if your jar name differs.
COPY --from=build /home/app/build/libs/*.jar ./app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
