package zeroday.Models.db.bootstrap

import zeroday.Queries.Login.UserRepository
import zeroday.Models.db.models.UserEntity
import zeroday.Controller.security.PasswordCrypto
import org.slf4j.LoggerFactory

object SuperAdminBootstrap {

    private val log = LoggerFactory.getLogger("SuperAdminBootstrap")

    fun init(userRepository: UserRepository) {

        val email = "admin@zcs.edu"

        // 1. Check if admin already exists
        val existing = userRepository.findByEmail(email)
        if (existing != null) {
            log.info("✅ Super admin already exists: $email")
            return
        }

        // 2. Generate salt + hash
        val salt = PasswordCrypto.generateSalt()
        val hash = PasswordCrypto.hash("admin123", salt)


        // 3. Create user
        val admin = UserEntity(
            id = 0L, // auto-generated by DB
            email = email,
            passwordHash = hash,
            passwordSalt = salt,
            role = "SUPER_ADMIN"
        )

        userRepository.insert(admin)

        log.info("🚀 Super admin created: $email / admin123")
    }
}
